### PR TITLE
Reduce spacing in Quiz View, and highlight right or wrong answers by background color

### PR DESCRIPTION
**Pull request by cralor**

### CODE REVIEW

**Comment by cralor** [comment]
@cbrech When you get a look at this, try scrolling in the Quiz View with the phone horizontal. I'm not getting that functionality at the moment.

**Comment by cralor** [comment]
On second look, I think the elements at the top are all a tad too close.

**Comment by cbrech** [comment]
Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-05-25 at 18 37 18

Looks a little squashed on ipads

**Comment by cbrech** [comment]
is it still WIP?

**Comment by cralor** [comment]
Yup I Was initially testing iPhone and was gonna bring it back out some

________________________________

**Pull request merged**
